language: cpp

branches:
  only:
    - master
    - dev
  
jobs:
  include:
    - name: MacOS
      os: osx
      osx_image: xcode12.2
      
      addons:
        homebrew:
          packages:
           - p7zip
#          - qt5
#          update: true
            
      script:
        - |
          if [ ! -f $HOME/Qt/5.14.2/clang_64/bin/qmake ]; then \
          pip install aqtinstall requests py7zr && \
          aqt install --outputdir $HOME/Qt 5.14.2 mac desktop clang_64 -m qtbase && \
          aqt tool --outputdir $HOME/Qt mac tools_ifw 4.0.1 qt.tools.ifw.40
          fi
        - bash deploy/build_macos.sh

    - name: Windows
      os: windows
            
      script:
        - dir "C:\"
        - dir "C:\Program Files (x86)\Microsoft Visual Studio"
        - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017"
        - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\"
        - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC"
        - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary"
        - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build"
        - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7"
        - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools"
        - |
          bash -c "if [ ! -f /C/Qt/5.14.2/msvc2017/bin/qmake ]; then \
          pip install aqtinstall requests py7zr && \
          aqt install --outputdir /C/Qt 5.14.2 windows desktop win32_msvc2017 -m qtbase && \
          aqt tool --outputdir /C/Qt windows tools_ifw 4.0.1 qt.tools.ifw.40
          fi"
        - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\VsDevCmd.bat"
        - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsamd64_x86.bat"
        - windows.bat

        
#before_cache:
#  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
#  # Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
#  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
  
cache:
  directories:
    - $HOME/Qt
    - C:\Qt
#    - $HOME/Library/Caches/Homebrew
#    - /usr/local/Cellar/qt