language: cpp

branches:
  only:
    - master
    - dev
  
jobs:
  include:
    - name: MacOS
      os: osx
      osx_image: xcode12.2
      
      addons:
        homebrew:
          packages:
           - p7zip
#          - qt5
#          update: true
            
      script:
        - if [ ! -f $HOME/Qt/5.14.2/clang_64/bin/qmake ]; then bash deploy/install-qt.sh -d $HOME/Qt --version 5.14.2 --toolchain clang_64 qtbase; fi
        - bash deploy/build_macos.sh

  include:
    - name: Windows
      os: windows
            
      script:
        - bash -c "if [ ! -f /C/Qt/5.14.2/msvc2017/bin/qmake ]; then bash deploy/install-qt.sh -d /C/Qt --version 5.14.2 --toolchain win32_msvc2017 qtbase; fi"
        
#before_cache:
#  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
#  # Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
#  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
  
cache:
  directories:
    - $HOME/Qt
    - C:\Qt
#    - $HOME/Library/Caches/Homebrew
#    - /usr/local/Cellar/qt