language: cpp

branches:
  only:
    - master
    - dev
    - /\d+\.\d+/
  
jobs:
  include:
    - name: MacOS
      os: osx
      osx_image: xcode12.5
      
      env:
        - QT_VERSION=5.15.2
        - QT_BIN_DIR=$HOME/Qt/$QT_VERSION/clang_64/bin
        - QIF_BIN_DIR=$QT_BIN_DIR/../../../Tools/QtInstallerFramework/4.0/bin
         
      script:
        - |
          if [ ! -f $HOME/Qt/$QT_VERSION/clang_64/bin/qmake ]; then \
          brew install p7zip && \
          pip3 install aqtinstall requests py7zr && \
          python3 -m aqt install --outputdir $HOME/Qt $QT_VERSION mac desktop clang_64 -m qtbase && \
          python3 -m aqt tool --outputdir $HOME/Qt mac tools_ifw 4.1 qt.tools.ifw.41;
          fi
        - bash deploy/build_macos.sh 

      deploy:
        provider: releases
        token: $GH_TOKEN
        skip_cleanup: true
        file:
        - "AmneziaVPN_unsigned.dmg"
        on:
          tags: true
          branch: master
    
    - name: Windows_x64
      os: windows
      
      env:
        - PATH=/c/Python39:/c/Python39/Scripts:$PATH
        - QT_VERSION=5.14.2
        - BUILD_ARCH="64"
        
      before_install:
        - if [ ! -f /C/Qt/$QT_VERSION/msvc2017_64/bin/qmake ]; then choco install python --version 3.9.1; fi
        
      script:
        - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build"
        - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools"
        - |
          if [ ! -f /C/Qt/$QT_VERSION/msvc2017_64/bin/qmake ]; then \
          pip3 install aqtinstall requests py7zr && \
          python -m aqt install --outputdir /C/Qt $QT_VERSION windows desktop win32_msvc2017_64 -m qtbase && \
          python -m aqt tool --outputdir /C/Qt windows tools_ifw 4.1 qt.tools.ifw.41; \
          fi
        - bash deploy/build_windows.sh
        
      deploy:
        provider: releases
        token: $GH_TOKEN
        skip_cleanup: true
        file:
        - "AmneziaVPN_x64.exe"
        on:
          tags: true
          branch: master

    - name: Windows_x32
      os: windows

      env:
        - PATH=/c/Python39:/c/Python39/Scripts:$PATH
        - QT_VERSION=5.14.2
        - BUILD_ARCH="32"

      before_install:
        - if [ ! -f /C/Qt/$QT_VERSION/msvc2017/bin/qmake ]; then choco install python --version 3.9.1; fi

      script:
        - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build"
        - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools"
        - |
          if [ ! -f /C/Qt/$QT_VERSION/msvc2017/bin/qmake ]; then \
          pip3 install aqtinstall requests py7zr && \
          python -m aqt install --outputdir /C/Qt $QT_VERSION windows desktop win32_msvc2017 -m qtbase && \
          python -m aqt tool --outputdir /C/Qt windows tools_ifw 4.1 qt.tools.ifw.41; \
          fi
          - bash deploy/build_windows.sh

      deploy:
        provider: releases
        token: $GH_TOKEN
        skip_cleanup: true
        file:
        - "AmneziaVPN_x32.exe"
        on:
          tags: true
          branch: master

deploy:
  skip_cleanup: true
  
before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
  # Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
  
cache:
  directories:
    - $HOME/Qt
    - /C/Qt
    - $HOME/Library/Caches/Homebrew
